import { useState, useEffect } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Search from './Search';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [q, setQ] = useState('41.32,19.88');
  const [isLoading, setLoading] = useState<Boolean>(false);

  useEffect(() => {
    setLoading(true);
    fetch(`https://api.weatherapi.com/v1/current.json?key=f27e122711544d58877135356222408&q=${q}&aqi=no`)
      .then((res) => res.json())
      .then((data) => {
        const { location } = data;
        console.log({data, location})
        setQ(`${location.lat},${location.lon}`);
        setLoading(false);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Search />
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
